### ISSUE TITLE
syntax err in translator gen for a removed property

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#345] opened 2017-09-05 17:17 UTC
The following example drops a property ("rating") between the source and target versions of a model. When you generate a version translator, the commented out line for the dropped property is missing a comma between the parameters of es:init-instance. Not a big deal since it is commented out (and probably not very likely to be uncommented), but it seems untidy of us.

This code is what we generate:
```
es:optional('NO TARGET'$rating)
```
I believe that is supposed to be (comma added before $rating):
```
es:optional('NO TARGET', $rating)
```
I generated this code using the following query.
```
'use strict';
const es = require('/MarkLogic/entity-services/entity-services');

const oldModel = 
  { "info":{
    "title":"test",
    "version":"0.0.1",
  },
  "definitions":{
    "MyType":{
      "properties":{
        "id":{"datatype":"string"},
        "rating":{"datatype":"string"}
      },
      "primaryKey":"id"
    }
}};
const newModel = 
{ "info":{
    "title":"test",
    "version":"0.0.2"
  },
  "definitions":{
    "MyType":{
      "properties":{
        "id":{"datatype":"string"}
      },
      "primaryKey":"id",
    }
}};

es.versionTranslatorGenerate(oldModel, newModel);
```

**Comment by kcoleman-marklogic** [comment] 2017-09-05 17:21
Actually, the more I think about this, the weirder it is. There's no declaration for `$rating`, either. Is the syntax error just supposed to be our way of saying "I have no idea wtf to do here. Fix me." 

Might it be better to just leave it out entirely?

**Comment by grechaw** [comment] 2017-09-06 17:19
hm, yes, looks like it needs a little reworking doesn't it.  I think it should be doable to get this right.  Not sure how I could have good coverage and have missed this, so I'll figure out what's up.

**Comment by grechaw** [comment] 2017-09-07 19:22
Turned out to be pretty simple -- just an off-by-one in a function to assist with padding.

**Comment by grechaw** [comment] 2017-09-07 19:23
Also, I am letting the 'let' expression through now for those properties which have been removed, so $rating is a legit variable in your example above.

**Comment by bsrikan** [comment] 2017-09-12 15:10
Seems fixed. Updated keys in functional tests. Will ship once merged to b9_0/develop

**Comment by bsrikan** [comment] 2017-09-14 19:39
Test run ok in regression. Good to ship from my side. Passing to you Kim for validation.

**Comment by kcoleman-marklogic** [comment] 2017-09-19 14:06
Looks OK to me, too.

**Closed** 2017-09-22 21:37 UTC
Labels: Bug, minor, ship
