### ISSUE TITLE
Should the new extract-array() function be in es:* module

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#76] opened 2016-07-13 22:26 UTC
Like es:optional, I'm finding another small utility function useful for both conversion modules.  This one includes an empty array for required properties, but an empty sequence for optional ones.

It's a fix for a bug where  optional array keys were populated regardless of the source's extraction of a value or not.

**Comment by grechaw** [comment] 2016-09-01 20:38
marked enhancement to assist in prioritizations

**Comment by grechaw** [comment] 2016-09-06 23:28
WG seems to think this is an OK idea.

**Comment by grechaw** [comment] 2016-09-07 23:03
We decided to move forward with this refactoring, as it's parallel to what we did for `es:optional`

**Comment by bsrikan** [comment] 2016-10-05 01:54
Changes for moving extract-array() to es:* module has been tested and seems to be working as expected. Keys were updated for instance-converter-generate() and version-translator-generate() tests. Test/key changes available in PR #175

**Comment by bsrikan** [comment] 2016-10-13 20:55
extract-array() working as expected after moving it to es:* module. Tests running successfully in regression. Shipping the bug.

**Closed** 2017-06-12 18:54 UTC
Labels: minor, ship, Task
