### ISSUE TITLE
Docs: Issues in Chapter 3

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#279] opened 2017-03-22 23:06 UTC
Issue1:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#chapter
Link to "Model Descriptor Basics" seems misplaced and redundant as it is covered under "Writing a Model Descriptor"

Issue2:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_73385
Actual:
For details, see Entity Type Definition Overview and Writing a Model Descriptor.
Expected:
For details, see Entity Type Definition Overview.

Since we already are in the "Writing a Model Descriptor" section, it doesnt add value to link to it for details IMO.

Issue3:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_73385
Actual:
In this example, the model named 'Example' defines and entity type is named 'Person'. 
Expected:
In this example, the model named 'Example' defines an entity type named 'Person'. 

Issue4:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_73385
XML Descriptor Example has tags not closed properly. Expected:
```
    </Person> <!-- /Person instead of /your-entity-type-name -->
  </es:definitions> <!-- / was missing -->
```

Issue5:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_60359
Actual:
The following example demonstates including a collation in an entity property definition.
Expected:
The following example demonstrates including a collation in an entity property definition.

Issue6:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_71519
Actual:
The value a property with IRI type must be a string that represents a sem:iri value.
Expected:
The value of a property with IRI type must be a string that represents a sem:iri value.

Issue7:
http://pubs.marklogic.com:8011/9.0/guide/entity-services/models#id_71519
Actual:
For example, the following entity type definition contains entity properties with four different simple types.
Expected:
For example, the following entity type definition defines an entity property called 'name' of type 'iri'.

**Comment by bsrikan** [comment] 2017-04-17 20:15
Kim seems to have pushed fixes for the issues in this bug. Updates are in Bugtrack # 45237. Assigning to self with label test.

**Comment by bsrikan** [comment] 2017-04-18 20:27
Issue#3 still seems not fixed.

**Comment by kcoleman-marklogic** [comment] 2017-04-18 22:18
You'll have to give more explicit directions on where or what the problem is if you think Issue 3 is not fixed. I see the following text on pubs:
>In this example, the model named 'Example' defines an entity type is named 'Person'. A Person entity has an id property.

I find no instances of "and entity" anywhere in that chapter.

**Comment by kcoleman-marklogic** [comment] 2017-04-18 22:24
Ah, I see it now. You are correct. There were two errors in that sentence. Sorry. It's really hard for me to pick out what's wrong when you just give me a second sentence and no explanation.

**Comment by kcoleman-marklogic** [comment] 2017-04-20 23:55
That's been fixed, Srikanth. Unless you want to look at the one line again, you can close this.

**Comment by bsrikan** [comment] 2017-04-21 05:58
Good to go!

**Closed** 2017-06-07 20:38 UTC
Labels: Bug, closed, minor
