### ISSUE TITLE
Additional Query won't grab json Entities

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/entity-services#359] opened 2017-11-14 21:01 UTC
The search-options generated by `search-options-generate` has `es:` namespaces in the path. That will not allow it to work with JSON entity instances.

Can we get this changed to support both?

current output for my particular entity:

```xml
<search:options xmlns:search="http://marklogic.com/appservices/search">
  <search:constraint name="entity-type">
    <search:value>
      <search:element ns="http://marklogic.com/entity-services" name="title"/>
    </search:value>
  </search:constraint>
  <search:constraint name="sku">
    <search:range type="xs:string" facet="true" collation="http://marklogic.com/collation/codepoint">
      <search:path-index xmlns:es="http://marklogic.com/entity-services">//es:instance/Product/sku</search:path-index>
    </search:range>
  </search:constraint>
  <search:constraint name="id">
    <search:value>
      <search:element ns="" name="id"/>
    </search:value>
  </search:constraint>
  <search:constraint name="price">
    <search:range type="xs:decimal" facet="true">
      <search:element ns="" name="price" xmlns:es="http://marklogic.com/entity-services"/>
    </search:range>
  </search:constraint>
  <search:values name="Product">
    <search:range type="xs:string" facet="true" collation="http://marklogic.com/collation/codepoint">
      <search:path-index xmlns:es="http://marklogic.com/entity-services">//es:instance/Product/sku</search:path-index>
    </search:range>
  </search:values>
  <search:values name="Order">
    <search:range type="xs:decimal" facet="true">
      <search:element ns="" name="price" xmlns:es="http://marklogic.com/entity-services"/>
    </search:range>
  </search:values>
  <!--Uncomment to return no results for a blank search, rather than the default of all results
 <search:term xmlns:search="http://marklogic.com/appservices/search">
  <search:empty apply="no-results"/>
</search:term> 
-->
  <search:values name="uris">
    <search:uri/>
  </search:values>
  <!--Change to 'filtered' to exclude false-positives in certain searches-->
  <search:search-option>unfiltered</search:search-option>
  <!--Modify document extraction to change results returned-->
  <search:extract-document-data selected="include">
    <search:extract-path xmlns:es="http://marklogic.com/entity-services">//es:instance/(Product|Order)</search:extract-path>
  </search:extract-document-data>
  <!--Change or remove this additional-query to broaden search beyond entity instance documents-->
  <search:additional-query>
    <cts:element-query xmlns:cts="http://marklogic.com/cts">
      <cts:element xmlns:es="http://marklogic.com/entity-services">es:instance</cts:element>
      <cts:true-query/>
    </cts:element-query>
  </search:additional-query>
  <!--To return facets, change this option to 'true' and edit constraints-->
  <search:return-facets>false</search:return-facets>
  <!--To return snippets, comment out or remove this option-->
  <search:transform-results apply="empty-snippet"/>
</search:options>
```

**Comment by grechaw** [comment] 2017-11-14 23:04
Yes, this is a bug.  I missed the change in 9.0-3 work.  I also ran into it the issue recently, annoying.  Of course the short term workaround is to edit the options.  If you generate a TDE template, you'll see the approach I took to address namespaces -- do you think something here would be similarly appropriate?

**Comment by grechaw** [comment] 2018-02-13 18:28
Since this was brought to my attention, ill get on having a fix in 9.05

**Comment by paxtonhare** [comment] 2018-02-14 03:25
Looks good to me.

**Comment by grechaw** [comment] 2018-02-14 18:29
So this fix is in develop now, assigned to @bsrikan to ensure testing coverage (which in this case is not too critical i think...)

**Comment by bsrikan** [comment] 2018-03-23 18:22
Tests added and running in regression. Shipping this.

**Closed** 2018-06-21 16:16 UTC
Labels: Bug, closed, minor

**Comment by epilith** [comment] 2020-07-15 14:32
This bugfix has caused another bug. Line 144 of [this file](https://github.com/marklogic/marklogic-data-hub/blob/4.x-develop/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/impl/hub-entities.xqy) causes problems with any namespace ending in es:. We have discovered this because we are using an entity with namespace `pasdes:` and it is replaced by `pasd*:` by this fix.

At the minimum this needs to be replaced by `fn:replace($n, "^es:$", "*:")` but ideally the namespace itself should be checked for the entity services namespace, rather than relying on the prefix to be set to a particular value.

**Comment by ehennum** [comment] 2020-07-15 16:22
@epilith , this repository no longer reflects the current state of Entity Services, which was moved into the internal repository for MarkLogic server (because Entity Services is distributed with a server).

The best way to report an issue with Entity Services now is to work with MarkLogic support to file the issue.

I'll explore having this repository removed now so other users don't make the natural assumption that it reflects the current state of the code or that it is the right place to file issues.  Apologies about the misdirect.
