### ISSUE TITLE
Validation error reporting is confusing

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/entity-services#121] opened 2016-08-20 00:25 UTC
It would be nice to include the property name or a line number with each validation error. For example, I managed to leave off the "es:" namespace qualifier from some of my property datatype elements, thusly:

``` xml
<es:model xmlns:es="http://marklogic.com/entity-services">
  <es:info>
    <es:title>CustomerModel</es:title>
    <es:version>0.0.1</es:version>
  </es:info>
  <es:definitions>
    <Name>
      <es:properties>
        <first>
          <datatype>string</datatype>
        </first>
        <middle>
          <datatype>string</datatype>
        </middle>
        <last>
          <datatype>string</datatype>
        </last>
      </es:properties>
      <es:required>first</es:required>
      <es:required>last</es:required>
    </Name>
  </es:definitions>
</es:model>
```

When I validated my model, I was greeted with the following message, which was, um, not as helpful as one might wish:

```
ES-MODEL-INVALID (err:FOER0000): If a property is not a reference, then it must have a datatype. If a property is not a reference, then it must have a datatype. If a property is not a reference, then it must have a datatype.
```

First off, it wasn't until I figured out what was wrong that I knew this wasn't just error reporting run amuck. I was thinking, "I heard you the first darned time!"

Second, if my model had not been trivial, this would not actually have helped me locate the problem since I can't tell what the offending properties are.

I'm thinkin' if we're going to report the validation errors via an exception rather than the way `xdmp:validate` does, then the error payload should ideally be a structure instead of (what I perceive as) a sequence of strings. Is that possible? Or, perhaps we already do something like that, and this is just QC piddling in my error-prone cheerios?

**Comment by grechaw** [comment] 2016-08-26 20:12
Good idea.  we should do this in EA-4.

**Comment by bsrikan** [comment] 2016-09-08 21:47
Another confusing error reporting scenario:

model has required property defined as `"required": "ProductID"` instead of `"required": [ "ProductID" ]`
es:model-validate() gave "`"Required" property ProductID doesn't exist.`" error message which is misleading since the real issue was that ProductID wasnt enclosed in [] as _required_ expects an array.

**Comment by grechaw** [comment] 2016-10-18 20:26
Added a patch to PR.  
I didn't address your last comment in it though @bsrikan so I'll probably add another commit to the PR before moving this to test.

**Comment by grechaw** [comment] 2016-10-18 20:51
OK I've added support for the last validation message that you posted, @bsrikan .

**Comment by bsrikan** [comment] 2016-10-21 06:31
Tests ran successfully in regression. Passing it to you @kcoleman-marklogic for review since you raised this bug.

**Comment by kcoleman-marklogic** [comment] 2016-10-24 22:18
It's certainly improved for the one error case I reported. If that's all the verification needed then this can be closed.

**Closed** 2017-09-22 21:38 UTC
Labels: Bug, minor, ship
